AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template

Resources:
  BillingBucketparserSNS:  # Added a colon here
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler  # Name of your Lambda handler function
      Runtime: python3.9  # Lambda runtime
      CodeUri: .  # This points to the current directory
      Timeout: 300
